#FROM alpine:latest AS build
#FROM debian:stable-slim AS build
FROM debian:oldstable-slim AS build
#RUN apk update
#RUN apk add --no-cache git
RUN apt update
RUN apt install -y git
RUN git clone https://github.com/matricks/bam
WORKDIR bam
RUN git checkout v0.4.0
#RUN apk add --no-cache gcc
RUN apt install -y build-essential
RUN ./make_unix.sh
