FROM alpine:latest AS build
RUN apk update
RUN apk add bash wget
RUN wget https://dot.net/v1/dotnet-install.sh
RUN chmod +x dotnet-install.sh
RUN ./dotnet-install.sh -c Current --runtime dotnet
RUN apk add git
RUN git clone https://github.com/Matodor/TeeSharp
WORKDIR TeeSharp
RUN git switch refactoring
RUN /root/.dotnet/dotnet restore
RUN /root/.dotnet/dotnet build
